/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnimateRouteImport } from './routes/animate'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate/image'
import { Route as ApiGenerateStatusRouteImport } from './routes/api/generate/status'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimateRoute = AnimateRouteImport.update({
  id: '/animate',
  path: '/animate',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate/image',
  path: '/api/generate/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStatusRoute = ApiGenerateStatusRouteImport.update({
  id: '/api/generate/status',
  path: '/api/generate/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate/video',
  path: '/api/generate/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animate': typeof AnimateRoute
  '/create': typeof CreateRoute
  '/creations': typeof CreationsRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/status': typeof ApiGenerateStatusRoute
  '/api/generate/video': typeof ApiGenerateVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animate': typeof AnimateRoute
  '/create': typeof CreateRoute
  '/creations': typeof CreationsRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/status': typeof ApiGenerateStatusRoute
  '/api/generate/video': typeof ApiGenerateVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animate': typeof AnimateRoute
  '/create': typeof CreateRoute
  '/creations': typeof CreationsRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/status': typeof ApiGenerateStatusRoute
  '/api/generate/video': typeof ApiGenerateVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/animate'
    | '/create'
    | '/creations'
    | '/api/generate/image'
    | '/api/generate/status'
    | '/api/generate/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/animate'
    | '/create'
    | '/creations'
    | '/api/generate/image'
    | '/api/generate/status'
    | '/api/generate/video'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/animate'
    | '/create'
    | '/creations'
    | '/api/generate/image'
    | '/api/generate/status'
    | '/api/generate/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnimateRoute: typeof AnimateRoute
  CreateRoute: typeof CreateRoute
  CreationsRoute: typeof CreationsRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateStatusRoute: typeof ApiGenerateStatusRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animate': {
      id: '/animate'
      path: '/animate'
      fullPath: '/animate'
      preLoaderRoute: typeof AnimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/image': {
      id: '/api/generate/image'
      path: '/api/generate/image'
      fullPath: '/api/generate/image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/status': {
      id: '/api/generate/status'
      path: '/api/generate/status'
      fullPath: '/api/generate/status'
      preLoaderRoute: typeof ApiGenerateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/video': {
      id: '/api/generate/video'
      path: '/api/generate/video'
      fullPath: '/api/generate/video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnimateRoute: AnimateRoute,
  CreateRoute: CreateRoute,
  CreationsRoute: CreationsRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateStatusRoute: ApiGenerateStatusRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
